#!/usr/bin/env python3
"""Learning-rate sweep for the bacterial-expression SFT, both arms at every point.

Why a sweep at all, given the dataset looks signal-poor: the observed failure is
not that the high arm fails to move, it is that the LOW arm moves just as far in
the SAME direction. Both arms collapse onto generic "looks like this dataset's
host" statistics. Learning rate is the knob most likely to change that, and the
direction is not obvious in advance -- a LARGER step could push each arm harder
onto its own data and increase the separation, or it could just overfit faster.
So we measure instead of guessing.

What is NOT worth sweeping: more steps. Both arms already reach their best
validation loss at epoch 3 of 60 and then rise monotonically, so the run is
early-stopping, not undertrained. The existing schedule also makes this hard to
see: cosine over max_epochs=60 while stopping at epoch 3 means the learning rate
never actually decays. Every point in this sweep uses max_epochs=12 so the
cosine completes, which is a fairer test of each peak LR.

Both arms are trained at every point because the quantity being optimised is the
SEPARATION between them, not either one's loss. A setting that improves the high
arm and the control equally has improved nothing.

    python configs/sweep/make_bacexp_sweep.py
"""
import os

BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LRS = ["1.0e-5", "3.0e-5", "1.0e-4", "3.0e-4"]     # 3.0e-5 is the original setting
ARMS = {"high": ("sft_high_bacteria_expression", 27, 220),
        "low": ("sft_low_bacteria_expression", 22, 165)}

TEMPLATE = """# Auto-generated by configs/sweep/make_bacexp_sweep.py -- do not edit by hand.
# Bacterial-expression SFT, {arm} arm, peak LR {lr}.
#
# Differences from configs/bacexp_sft.yaml, applied identically to every sweep
# point so that only the learning rate varies:
#   max_epochs 60 -> 12   the original cosine never decayed, because both arms
#                         early-stop around epoch 3; over 12 epochs the schedule
#                         actually completes.
#   warmup_steps 10 -> 20 one warmup per ~epoch rather than a third of one.
#   early_stop_patience 8 -> 6
domain: bacexp_sweep_{arm}_lr{tag}
data_dir: sft/data
out_dir: runs/bacexp_sweep/{arm}_lr{tag}
train_lmdb: {stem}_train.lmdb
val_lmdb: {stem}_val.lmdb
val_full_lmdb: {stem}_val.lmdb
init_ckpt: runs/bacteria/model_best.pt

num_workers: 4
token_budget: 32768
grad_accum: 1
seed: 42

schedule: cosine
lr: {lr}
min_lr: {min_lr}
warmup_steps: 20
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0

max_epochs: 12
min_epochs: 3
early_stop_patience: 6
early_stop_min_delta: 0.002
early_stop_burn_in_frac: 0.10
eval_interval: {ev}
eval_seqs: {nval}
log_interval: 5

grad_norm_skip_factor: 0.0
max_hours: 1.0
keep_last: 2
compile: true
dtype: bfloat16

model:
  pos_encoding: rope
  block_size: 2048
  n_layer: 24
  n_head: 16
  n_embd: 1024
  bias: false
  dropout: 0.1
"""

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    made = []
    for lr in LRS:
        tag = lr.replace(".0e-", "e")           # 3.0e-5 -> 3e-5
        for arm, (stem, ev, nval) in ARMS.items():
            m, e = lr.split("e-")
            min_lr = f"{float(m):.1f}e-{int(e)+1}"          # one decade below peak
            p = os.path.join(here, f"bacexp_{arm}_lr{tag}.yaml")
            with open(p, "w") as fh:
                fh.write(TEMPLATE.format(arm=arm, lr=lr, tag=tag, stem=stem,
                                         ev=ev, nval=nval, min_lr=min_lr))
            made.append(p)
    for p in made:
        print("  " + os.path.relpath(p, os.path.join(here, "..", "..")))
    print(f"{len(made)} configs")


if __name__ == "__main__":
    main()
